# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2a4b7e8e4924ec689826d9c1a0134db6f569259df92b379b105d958fbefecb77244f312bfcb7defdc1889d2181c6024efb1a902b6e472cc6185bd0019c7fbfdb

test:
  secret_key_base: e157e91d74d6750818b48e50fc4c47f479609f57acee798dd54204d70e26f0d754689c9ece602cd336fb8ea6cffe46c2130b6071ddd1007eb73426491d7c5984

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
