# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 23f9a0a4e29eff412e4fe3e0b9e3f23d2d8d9d68ced36d574bb1882fd6a4df2c1f432a55d2aef264e4a94fbe3fecb88d582722f24c5d80db640ba9a7d1a9a3fe

test:
  secret_key_base: d47d82193d91726eaecc0fdcd115b28c9971cd15528c12a44eac35157fd4e3a35c67240d5990c642144d0f3852b28f1d607c98ffc81d6a51fea77747a4e6485f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
